phrase:
  access_token: 961ac3df3cc14c22f3f4ed2075f7a444b69922e9f2c4837e1bc1be3266b5e4cd
  project_id: 47b1f46fd10f7f99a4ab6f1b5c726b7d
  
  push:
    sources:
      - file: ./simple_json.json
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true
          autotranslate: true

  pull:
    targets:
      - file: ./simple_json.json
        params:
          file_format: simple_json
