phrase:
  access_token: 8a41eebd2ebce45c68c556356578a820c03eae659b0f91acb5c68c99e2d9c1f8
  project_id: 47b1f46fd10f7f99a4ab6f1b5c726b7d
  
  push:
    sources:
      - file: ./simple_json.json
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true
          autotranslate: true

  pull:
    targets:
      - file: ./simple_json.json
        params:
          file_format: simple_json
